clear;
x1 = DTS(0 : 9, [ones(1, 5) zeros(1, 5)]);
h1 = DTS(0 : 4, [1 -1 3 1 0]);
h2 = DTS(0 : 4, [0 2 5 4 -1]);
y1 = x1 * (h1 + h2);
y2 = x1 * h1 + x1 * h2;
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "x_1[n]", "grid", "on"), ...
    { x1.sInf("x_1[n]", "#01AFEE") }, ...
    struct("xlabel", "n", "ylabel", "h_1[n]", "grid", "on"), ...
    { h1.sInf("h_1[n]", "#2E9F79") }, ...
    struct("xlabel", "n", "ylabel", "h_2[n]", "grid", "on"), ...
    { h2.sInf("h_2[n]", "#2E9F79") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { ...
        y1.sInf("x_1[n] * (h_1[n] + h_2[n])", "", "b"), ...
        y2.sInf("x_1[n] * h_1[n] + x_1[n] * h_2[n]", "", "g--") ...
    } ...
);
