clear;
n0 = 2;
x1 = DTS(0 : 9, [ones(1, 5) zeros(1, 5)]);
he1 = DTS(0 : 4, [1 -1 3 1 0]);
he2 = he1.shift(-n0);
ye1 = x1 * he1;
ye2 = x1 * he2;
ye1s = ye1.shift(-n0);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { ye1.sInf("y_{e1}[n] = x_1[n] * h_1[n]", "#01AFEE") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on", "xlim", [0 14]), ...
    { ye2.sInf("y_{e2}[n] = x_1[n] * h_1[n - n_0]", "#2E9F79") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on", "xlim", [0 14]), ...
    { ye1s.sInf("y_{e1}[n - n_0]", "#5574C6") } ...
);
