clear;
x1 = DTS(-1 : 5, [0 1 0 0 0 0 0]);
x2 = x1.shift(-1);
x3 = x1 + 2 .* x2;
w1 = x1.filter([1 -1 -1], [1]).cut(0 : 5);
w2 = x2.filter([1 -1 -1], [1]).cut(0 : 5);
w3 = x3.filter([1 -1 -1], [1]).cut(0 : 5);
w4 = w1 + 2 .* w2;
y1 = x1.func('cos').cut(0 : 5);
y2 = x2.func('cos').cut(0 : 5);
y3 = x3.func('cos').cut(0 : 5);
y4 = y1 + 2 .* y2;
n = DTS(0 : 5, 0 : 5);
z1 = n .* x1; z1 = z1.cut(0 : 5);
z2 = n .* x2; z2 = z2.cut(0 : 5);
z3 = n .* x3; z3 = z3.cut(0 : 5);
z4 = z1 + 2 .* z2;
figure(1);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "w[n]", "grid", "on"), ...
    { w1.sInf("w_1[n]", "#331199") }, ...
    struct("xlabel", "n", "ylabel", "w[n]", "grid", "on"), ...
    { w2.sInf("w_2[n]", "#993366") }, ...
    struct("xlabel", "n", "ylabel", "w[n]", "grid", "on"), ...
    { w3.sInf("w_3[n]", "#CC4488") }, ...
    struct("xlabel", "n", "ylabel", "w[n]", "grid", "on"), ...
    { w4.sInf("w_1[n] + 2w_2[n]", "#FFAA55") } ...
);
figure(2);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { y1.sInf("y_1[n]", "#331199") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { y2.sInf("y_2[n]", "#993366") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { y3.sInf("y_3[n]", "#CC4488") }, ...
    struct("xlabel", "n", "ylabel", "y[n]", "grid", "on"), ...
    { y4.sInf("y_1[n] + 2y_2[n]", "#FFAA55") } ...
);
figure(3);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "z[n]", "grid", "on"), ...
    { z1.sInf("z_1[n]", "#331199") }, ...
    struct("xlabel", "n", "ylabel", "z[n]", "grid", "on"), ...
    { z2.sInf("z_2[n]", "#993366") }, ...
    struct("xlabel", "n", "ylabel", "z[n]", "grid", "on"), ...
    { z3.sInf("z_3[n]", "#CC4488") }, ...
    struct("xlabel", "n", "ylabel", "z[n]", "grid", "on"), ...
    { z4.sInf("z_1[n] + 2z_2[n]", "#FFAA55") } ...
);
