clear;
delta = DTS(0 : 19, [1 zeros(1, 19)]);
h1 = delta.filter([1], [1 -0.6]);
n = DTS(0 : 19, 0 : 19);
h2 = 0.6 .^ (n .* (n + 1) ./ 2);
figure(1);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "h_1[n]", "grid", "on", "xlim", [0 19]), ...
    { h1.sInf("h_1[n]", "#01AFEE") }, ...
    struct("xlabel", "n", "ylabel", "h_2[n]", "grid", "on", "xlim", [0 19]), ...
    { h2.sInf("h_2[n]", "#2E9F79") } ...
);
