clear;
step = DTS(0 : 19, ones(1, 20));
s1 = step.filter([1], [1 -0.6]);
s2 = step;
for i = 2 : 20
    s2.value(i) = 0.6 ^ (i - 1) * s2.value(i - 1) + s2.value(i);
end
figure(1);
DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "s_1[n]", "grid", "on", "xlim", [0 19]), ...
    { s1.sInf("s_1[n]", "#01AFEE") }, ...
    struct("xlabel", "n", "ylabel", "s_2[n]", "grid", "on", "xlim", [0 19]), ...
    { s2.sInf("s_2[n]", "#2E9F79") } ...
);
