clear;

x1 = DTS.Periodic({-10, 70}, 1);
x2 = DTS.Periodic({-10, 70}, [ones(1, 8), zeros(1, 8)]);
x3 = DTS.Periodic({-10, 70}, [ones(1, 8), zeros(1, 24)]);

v = [0 63];
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "x_1[n]", "xlim", v, "grid", "on"), ...
    { x1.sInf("x_1[n]", "r", ".") }, ...
    struct("xlabel", "t", "ylabel", "x_2[n]", "xlim", v, "grid", "on"), ...
    { x2.sInf("x_2[n]", "g", ".") }, ...
    struct("xlabel", "t", "ylabel", "x_3[n]", "xlim", v, "grid", "on"), ...
    { x3.sInf("x_3[n]", "b", ".") } ...
);
