clear;

a1 = DTS(DTS(ones(1, 8)).dtfs);
a2 = DTS(DTS([ones(1, 8), zeros(1, 8)]).dtfs);
a3 = DTS(DTS([ones(1, 8), zeros(1, 24)]).dtfs);

figure(1);
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "a_1[n]", "xlim", [0 7], "grid", "on"), ...
    { a1.func('real').sInf("a_1[n]_{real}", "", "."), a1.func('imag').sInf("a_1[n]_{imag}", "", ".") }, ...
    struct("xlabel", "t", "ylabel", "a_2[n]", "xlim", [0 15], "grid", "on"), ...
    { a2.func('real').sInf("a_2[n]_{real}", "", "."), a2.func('imag').sInf("a_2[n]_{imag}", "", ".") }, ...
    struct("xlabel", "t", "ylabel", "a_3[n]", "xlim", [0 31], "grid", "on"), ...
    { a3.func('real').sInf("a_3[n]_{real}", "", "."), a3.func('imag').sInf("a_3[n]_{imag}", "", ".") } ...
);

figure(2);
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "a_1[n]", "xlim", [0 7], "grid", "on"), ...
    { a1.func('abs').sInf("|a_1[n]|") }, ...
    struct("xlabel", "t", "ylabel", "a_2[n]", "xlim", [0 15], "grid", "on"), ...
    { a2.func('abs').sInf("|a_2[n]|") }, ...
    struct("xlabel", "t", "ylabel", "a_3[n]", "xlim", [0 31], "grid", "on"), ...
    { a3.func('abs').sInf("|a_3[n]|") } ...
);
