clear;

a3 = DTS(circshift(DTS([ones(1, 8), zeros(1, 24)]).dtfs, 15)).shift(15);
x3_2 = a3.cut(-2 : 2).cut(-15 : 16).idtfs;
x3_8 = a3.cut(-8 : 8).cut(-15 : 16).idtfs;
x3_12 = a3.cut(-12 : 12).cut(-15 : 16).idtfs;
x3_all = a3.idtfs;

v = [0 31];
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "x_{3(2)}[n]", "xlim", v, "grid", "on"), ...
    { x3_2.func('real').sInf("x_{3(2)}[n]") }, ...
    struct("xlabel", "t", "ylabel", "x_{3(8)}[n]", "xlim", v, "grid", "on"), ...
    { x3_8.func('real').sInf("x_{3(8)}[n]") }, ...
    struct("xlabel", "t", "ylabel", "x_{3(12)}[n]", "xlim", v, "grid", "on"), ...
    { x3_12.func('real').sInf("x_{3(12)}[n]") }, ...
    struct("xlabel", "t", "ylabel", "x_{3(all)}[n]", "xlim", v, "grid", "on"), ...
    { x3_all.func('real').sInf("x_{3(all)}[n]") } ...
);
