clear;

a1 = [1, -0.8]; b1 = [1];
a2 = [1, 0.8]; b2 = [1];
S = 1024;
[h1, w1] = freqz(b1, a1, S, 'whole');
[h2, w2] = freqz(b2, a2, S, 'whole');

DTS.Figures("v", ...
    struct("xlabel", "\omega", "ylabel", "H_1(\omega)", "xlim", [0, 2 * pi], "grid", "on"), ...
    { DTS(w1, abs(h1)).sInf("H_1(\omega)", "r", "", "plot") }, ...
    struct("xlabel", "\omega", "ylabel", "H_2(\omega)", "xlim", [0, 2 * pi], "grid", "on"), ...
    { DTS(w2, abs(h2)).sInf("H_2(\omega)", "b", "", "plot") } ...
);
