clear;

a_x = DTS([0, 3 / 4, zeros(1, 7), -1 / 2, 0, - 1 / 2, zeros(1, 7), 3 / 4]);
x_20 = a_x.idtfs.func('real');
x = DTS.Periodic({-20, 99}, x_20.value);

DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "x_{20}[n]", "grid", "on"), ...
    { x_20.sInf("x_{20}[n]", "b") }, ...
    struct("xlabel", "n", "ylabel", "x[n]", "grid", "on"), ...
    { x.sInf("x[n]", "r", ".") } ...
);
