clear;

a1 = [1, -0.8]; b1 = [1];
a2 = [1, 0.8]; b2 = [1];
a_x = DTS([0, 3 / 4, zeros(1, 7), -1 / 2, 0, - 1 / 2, zeros(1, 7), 3 / 4]);
x_20 = a_x.idtfs.func('real');
x = DTS.Periodic({-20, 99}, x_20.value);
y1 = x.filter(b1, a1);
y2 = x.filter(b2, a2);

DTS.Figures("v", ...
    struct("xlabel", "n", "ylabel", "x[n]", "xlim", [0 99], "grid", "on"), ...
    { x.sInf("x[n]", "g", ".") }, ...
    struct("xlabel", "n", "ylabel", "y_1[n]", "xlim", [0 99], "grid", "on"), ...
    { y1.sInf("y_1[n]", "r", ".") }, ...
    struct("xlabel", "n", "ylabel", "y_2[n]", "xlim", [0 99], "grid", "on"), ...
    { y2.sInf("y_2[n]", "b", ".") } ...
);
