clear;

S = 1000;
x2 = DTS.Identity({0, 20}, S).func('cos').func('sign');
apos_k = DTS(2 * DTS(DTS.Identity({1, 10}) .* pi ./ 2).func('sin') ./ (DTS.Identity({1, 10}) .* pi)).shift(-1).stretch(2).value;
aneg_k = DTS(2 * DTS(DTS.Identity({-10, -1}) .* pi ./ 2).func('sin') ./ (DTS.Identity({-10, -1}) .* pi)).shift(1).stretch(-2).value;
ssum = DTS({0, 0}, 0, S);
Idn = DTS.Identity({-5, 20}, S);
for I = 1 : 5
    k = 2 * I - 1;
    s(I) = apos_k(I) * DTS(1j * k * Idn).func('exp') + aneg_k(I) * DTS(-1j * k * Idn).func('exp');
    ssum = ssum + s(I);
end

figure(1);
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "s(t)", "grid", "on"), { s(1).cut({0, 20}).sInf("s_1(t)", "b", "", "plot") }, ...
    struct("xlabel", "t", "ylabel", "s(t)", "grid", "on"), { s(2).cut({0, 20}).sInf("s_2(t)", "b", "", "plot") }, ...
    struct("xlabel", "t", "ylabel", "s(t)", "grid", "on"), { s(3).cut({0, 20}).sInf("s_3(t)", "b", "", "plot") }, ...
    struct("xlabel", "t", "ylabel", "s(t)", "grid", "on"), { s(4).cut({0, 20}).sInf("s_4(t)", "b", "", "plot") }, ...
    struct("xlabel", "t", "ylabel", "s(t)", "grid", "on"), { s(5).cut({0, 20}).sInf("s_5(t)", "b", "", "plot") } ...
);

figure(2);
DTS.Figures("v", ...
    struct("xlabel", "t", "ylabel", "f(t)", "grid", "on"), ...
    { x2.cut({0, 20}).sInf("x(t)", "r", "", "plot"), ssum.cut({0, 20}).sInf("x'(t)", "b", "", "plot") } ...
);
